* Fixed Priyom API Exception: AttributeError: 'NoneType' object has no attribute 'stormSortArgs'   This fixes a regression introduced by 557a0e5cde689538b6fdd8057c88404fdaf4c59f